In [1]:
# this file is mainly used for case study of the top 50 breast and lung neoplasms
# using two authoritative data sets, dbDEMC and miR2Disease
import pandas as pd
import numpy as np

In [ ]:
# fetching the breast and lung neoplasms data from known associations with their association scores
eval_df = pd.read_csv('datasets/predicted_associations/evaluation_breast_lung_knownpred_scores_jan9.csv')

In [3]:
eval_df

     MiRNA  Disease     Score
0        7       50  0.000000
1      117       50  0.182044
2      118       50  0.181881
3      119       50  0.156858
4       59       50  0.146652
..     ...      ...       ...
329     55      236  0.000000
330     56      236  0.000070
331     57      236  0.000081
332    280      236  0.000000
333    343      236  0.000000

[334 rows x 3 columns]

In [4]:
# categorizing breast and lung neoplasms data
breast_df = eval_df[eval_df['Disease']==50]
lung_df = eval_df[eval_df['Disease']==236]
breast_df = breast_df.sort_values(by='Score', ascending=False)
lung_df = lung_df.sort_values(by='Score', ascending=False)

In [5]:
breast_df, lung_df

(     MiRNA  Disease     Score
 112      6       50  0.236587
 95      46       50  0.195291
 1      117       50  0.182044
 2      118       50  0.181881
 86      43       50  0.176262
 ..     ...      ...       ...
 143    146       50  0.000000
 63      71       50  0.000000
 140     87       50  0.000000
 65      32       50  0.000000
 0        7       50  0.000000

 [202 rows x 3 columns],
      MiRNA  Disease     Score
 279     46      236  0.000207
 225    121      236  0.000205
 265     39      236  0.000184
 216     23      236  0.000170
 291      6      236  0.000165
 ..     ...      ...       ...
 253     32      236  0.000000
 251     71      236  0.000000
 250    345      236  0.000000
 249    357      236  0.000000
 333    343      236  0.000000

 [132 rows x 3 columns])

In [6]:
# getting top 50 samples
breast_df_top50 = breast_df.head(50)
lung_df_top50 = lung_df.head(50)

In [7]:
breast_df_top50.shape, lung_df_top50.shape

((50, 3), (50, 3))

In [8]:
breast_df_top50

     MiRNA  Disease     Score
112      6       50  0.236587
95      46       50  0.195291
1      117       50  0.182044
2      118       50  0.181881
86      43       50  0.176262
79      38       50  0.175549
88      14       50  0.166729
80      39       50  0.166075
3      119       50  0.156858
40      10       50  0.155588
92     223       50  0.150362
15      23       50  0.148297
4       59       50  0.146652
117    230       50  0.139446
160    251       50  0.134306
30     209       50  0.119305
55      13       50  0.119278
186    271       50  0.112068
91      45       50  0.111734
29     121       50  0.107791
131    237       50  0.101365
99     226       50  0.099962
69      35       50  0.094708
175    261       50  0.090291
110    229       50  0.090094
123    155       50  0.088101
145    241       50  0.082014
106     77       50  0.080446
24      24       50  0.079476
66     218       50  0.078042
129     82       50  0.077750
32      17       50  0.071717
124     50       50  0.071460
94     224       50  0.070979
44     212       50  0.069679
21     207       50  0.069679
77     220       50  0.069679
46      69       50  0.068984
81     221       50  0.066226
13     140       50  0.064967
61      31       50  0.064200
78      37       50  0.062145
109    228       50  0.061701
12     120       50  0.060614
39       9       50  0.060522
42      18       50  0.060247
171    257       50  0.059131
177    263       50  0.059131
126    233       50  0.059131
38       8       50  0.057299

In [9]:
lung_df_top50

     MiRNA  Disease     Score
279     46      236  0.000207
225    121      236  0.000205
265     39      236  0.000184
216     23      236  0.000170
291      6      236  0.000165
311    241      236  0.000149
276    223      236  0.000144
237     10      236  0.000126
263     37      236  0.000119
264     38      236  0.000119
269     43      236  0.000117
236      9      236  0.000116
238     18      236  0.000116
270     14      236  0.000114
240     69      236  0.000106
297    155      236  0.000100
205    119      236  0.000088
204    118      236  0.000086
267     42      236  0.000085
203    117      236  0.000084
252     72      236  0.000083
206     59      236  0.000082
331     57      236  0.000081
278    224      236  0.000079
233    165      236  0.000078
330     56      236  0.000070
227     17      236  0.000067
262     75      236  0.000065
298    156      236  0.000059
222    172      236  0.000054
221     24      236  0.000052
248     31      236  0.000051
301    201      236  0.000050
299     50      236  0.000048
296     81      236  0.000048
288     77      236  0.000047
271     44      236  0.000041
326    275      236  0.000038
215    140      236  0.000036
213    203      236  0.000034
287     49      236  0.000032
246    145      236  0.000029
234    157      236  0.000027
247     30      236  0.000024
303    130      236  0.000019
232    122      236  0.000016
283    168      236  0.000012
212     21      236  0.000006
256      2      236  0.000006
307     88      236  0.000002

In [ ]:
# reading miRNA names
mirna_names = pd.read_csv('datasets/1.miRNA_disease_association/miRNA name.csv', header=None)

In [11]:
mirna_names

       0             1
0      1  hsa-mir-125a
1      2  hsa-mir-196a
2      3  hsa-mir-499a
3      4   hsa-mir-198
4      5   hsa-mir-29a
..   ...           ...
490  491  hsa-mir-550b
491  492  hsa-mir-1227
492  493  hsa-mir-1229
493  494   hsa-mir-944
494  495  hsa-mir-518a

[495 rows x 2 columns]

In [12]:
breast_df_top50['mirna_name'] = ''
lung_df_top50['mirna_name'] = ''

/Users/momanyibiffon/opt/anaconda3/envs/tf/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/momanyibiffon/opt/anaconda3/envs/tf/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
# fetching mirna names
for m in range(len(mirna_names)):
    for n in range(len(lung_df_top50)):
            if breast_df_top50.iloc[n, 0] == mirna_names.iloc[m, 0]:
                breast_df_top50.iloc[n, 3] = mirna_names.iloc[m, 1]
            if lung_df_top50.iloc[n, 0] == mirna_names.iloc[m, 0]:
                lung_df_top50.iloc[n, 3] = mirna_names.iloc[m, 1]

/Users/momanyibiffon/opt/anaconda3/envs/tf/lib/python3.7/site-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
# saving breast and lung neoplasms data with actual associated miRNA names
breast_df_top50.to_csv("datasets/predicted_associations/case_study/breast_df_top50_with_names.csv", index=False)
lung_df_top50.to_csv("datasets/predicted_associations/case_study/lung_df_top50_with_names.csv", index=False)

In [16]:
breast_df_top50

     MiRNA  Disease     Score    mirna_name
112      6       50  0.236587   hsa-mir-29b
95      46       50  0.195291   hsa-mir-221
1      117       50  0.182044    hsa-let-7b
2      118       50  0.181881    hsa-let-7c
86      43       50  0.176262   hsa-mir-20a
79      38       50  0.175549  hsa-mir-200b
88      14       50  0.166729    hsa-mir-21
80      39       50  0.166075  hsa-mir-200c
3      119       50  0.156858    hsa-let-7d
40      10       50  0.155588   hsa-mir-145
92     223       50  0.150362   hsa-mir-218
15      23       50  0.148297   hsa-mir-10b
4       59       50  0.146652    hsa-let-7e
117    230       50  0.139446  hsa-mir-302b
160    251       50  0.134306  hsa-mir-450b
30     209       50  0.119305  hsa-mir-1323
55      13       50  0.119278    hsa-mir-16
186    271       50  0.112068   hsa-mir-608
91      45       50  0.111734   hsa-mir-215
29     121       50  0.107791   hsa-mir-132
131    237       50  0.101365  hsa-mir-320e
99     226       50  0.099962  hsa-mir-2355
69      35       50  0.094708   hsa-mir-194
175    261       50  0.090291  hsa-mir-516b
110    229       50  0.090094   hsa-mir-299
123    155       50  0.088101   hsa-mir-30d
145    241       50  0.082014  hsa-mir-365b
106     77       50  0.080446   hsa-mir-27a
24      24       50  0.079476   hsa-mir-126
66     218       50  0.078042  hsa-mir-1915
129     82       50  0.077750  hsa-mir-320c
32      17       50  0.071717  hsa-mir-133b
124     50       50  0.071460    hsa-mir-31
94     224       50  0.070979    hsa-mir-22
44     212       50  0.069679  hsa-mir-1471
21     207       50  0.069679  hsa-mir-1258
77     220       50  0.069679   hsa-mir-200
46      69       50  0.068984  hsa-mir-148a
81     221       50  0.066226   hsa-mir-202
13     140       50  0.064967   hsa-mir-107
61      31       50  0.064200   hsa-mir-183
78      37       50  0.062145  hsa-mir-200a
109    228       50  0.061701   hsa-mir-298
12     120       50  0.060614  hsa-mir-106b
39       9       50  0.060522   hsa-mir-143
42      18       50  0.060247  hsa-mir-146a
171    257       50  0.059131   hsa-mir-510
177    263       50  0.059131  hsa-mir-519d
126    233       50  0.059131  hsa-mir-3186
38       8       50  0.057299   hsa-mir-141

In [18]:
lung_df_top50

     MiRNA  Disease     Score    mirna_name
279     46      236  0.000207   hsa-mir-221
225    121      236  0.000205   hsa-mir-132
265     39      236  0.000184  hsa-mir-200c
216     23      236  0.000170   hsa-mir-10b
291      6      236  0.000165   hsa-mir-29b
311    241      236  0.000149  hsa-mir-365b
276    223      236  0.000144   hsa-mir-218
237     10      236  0.000126   hsa-mir-145
263     37      236  0.000119  hsa-mir-200a
264     38      236  0.000119  hsa-mir-200b
269     43      236  0.000117   hsa-mir-20a
236      9      236  0.000116   hsa-mir-143
238     18      236  0.000116  hsa-mir-146a
270     14      236  0.000114    hsa-mir-21
240     69      236  0.000106  hsa-mir-148a
297    155      236  0.000100   hsa-mir-30d
205    119      236  0.000088    hsa-let-7d
204    118      236  0.000086    hsa-let-7c
267     42      236  0.000085   hsa-mir-205
203    117      236  0.000084    hsa-let-7b
252     72      236  0.000083   hsa-mir-18b
206     59      236  0.000082    hsa-let-7e
331     57      236  0.000081    hsa-mir-95
278    224      236  0.000079    hsa-mir-22
233    165      236  0.000078   hsa-mir-138
330     56      236  0.000070    hsa-mir-93
227     17      236  0.000067  hsa-mir-133b
262     75      236  0.000065   hsa-mir-19b
298    156      236  0.000059   hsa-mir-30e
222    172      236  0.000054   hsa-mir-127
221     24      236  0.000052   hsa-mir-126
248     31      236  0.000051   hsa-mir-183
301    201      236  0.000050   hsa-mir-326
299     50      236  0.000048    hsa-mir-31
296     81      236  0.000048   hsa-mir-30c
288     77      236  0.000047   hsa-mir-27a
271     44      236  0.000041   hsa-mir-210
326    275      236  0.000038   hsa-mir-638
215    140      236  0.000036   hsa-mir-107
213    203      236  0.000034  hsa-mir-103b
287     49      236  0.000032   hsa-mir-26b
246    145      236  0.000029  hsa-mir-181c
234    157      236  0.000027   hsa-mir-140
247     30      236  0.000024   hsa-mir-182
303    130      236  0.000019   hsa-mir-335
232    122      236  0.000016   hsa-mir-137
283    168      236  0.000012   hsa-mir-23a
212     21      236  0.000006  hsa-mir-103a
256      2      236  0.000006  hsa-mir-196a
307     88      236  0.000002   hsa-mir-34a